print ("##############################")
print ("#                            #")
print ("#    Putri Fatima Az'hara    #")
print ("#        2410817120001       #")
print ("#                            #")
print ("##############################")